// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsxwdzkumgwoqvkgxdkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzeHdkemt1bWd3b3F2a2d4ZGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjI0OTYsImV4cCI6MjA2NDM5ODQ5Nn0.WksgHF692sSnkXMZ8y0WOHsWwxfS3DJi9eQyFUf1ps4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});